local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local ClientDataCreator = require(script.Parent:WaitForChild("ClientDataCreator"))
local Util = require(Modules:WaitForChild("Util"))
--local PlayerData : ClientDataCreator.Data = ClientDataCreator.get("Players", Players.LocalPlayer, 5)

--PlayerData:listen("Coins", function(oldValue, newValue)
--	print(oldValue, newValue)
--end)